apiVersion: v1
kind: Service
metadata:
  name: easy-challenge-api
spec:
  type: NodePort
  selector:
    app: easy-challenge-api
  ports:
  - protocol: TCP
    port: 12544
    targetPort: 8000
    nodePort: 30008