apiVersion: v1
kind: Service
metadata:
  name: easy-challenge-db
spec:
  type: NodePort
  selector:
    app: easy-challenge-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30009