apiVersion: v1
kind: Service
metadata:
  name: challenge-server
spec:
  type: NodePort
  selector:
    app: challenge-server
  ports:
  - protocol: TCP
    port: 30007
    targetPort: 12543
    nodePort: 30007