apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-challenge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easy-challenge-api
  template:
    metadata:
      labels:
        app: easy-challenge-api
    spec:
      containers:
      - name: fastapi-app
        image: fastapi-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000